In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../src/Chocolate_Sales.csv")
df.head()

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Order_ID         200000 non-null  object
 1   Product          200000 non-null  object
 2   Country          200000 non-null  object
 3   Channel          200000 non-null  object
 4   Salesperson      200000 non-null  object
 5   Order_Date       199563 non-null  object
 6   Discount_Pct     199511 non-null  float64
 7   Price_per_Box    199543 non-null  float64
 8   Marketing_Spend  199539 non-null  float64
 9   Boxes_Shipped    200000 non-null  int64
 10  Amount           200000 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 16.8+ MB

In [5]:
df.describe()

        Discount_Pct  Price_per_Box  Marketing_Spend  Boxes_Shipped
count  199511.000000  199543.000000    199539.000000  200000.000000
mean       13.107457       5.911507        95.450141     139.584105
std         6.374477       4.954976        66.243760     118.665393
min         0.000000       2.040000         4.300000   -1642.000000
25%         8.300000       2.950000        52.270000      67.000000
50%        12.600000       3.280000        78.850000     113.000000
75%        17.500000       4.570000       118.710000     180.000000
max        38.300000      21.650000       798.222443    3811.000000

In [7]:
df.columns

Index(['Order_ID', 'Product', 'Country', 'Channel', 'Salesperson',
       'Order_Date', 'Discount_Pct', 'Price_per_Box', 'Marketing_Spend',
       'Boxes_Shipped', 'Amount'],
      dtype='object')

In [12]:
X = df.drop(columns=["Amount", "Order_ID", "Order_Date"])
y = df["Amount"]

In [13]:
X = pd.get_dummies(X, drop_first=True)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [17]:
from baseline_model import train_baseline, save_metrics

In [18]:
model, metrics = train_baseline()
save_metrics(metrics)
metrics

{'model': 'baseline_ridge_regression',
 'mae': 107.67273086851367,
 'rmse': 207.36984574043265,
 'r2': 0.6901929868908425,
 'train_rows': 160000,
 'test_rows': 40000}